- platform: rfxtrx
  automatic_add: True
  devices:
    0a52080601010038480349:
      name: Kjoleskap
    0a520805020200cb1e0249:
      name: Stue_Vindu
    0a52080103010012260259:
      name: Ute_soverom
    0a5208030401001f1d0259:
      name: Ute_veranda
    0a52080705020095220269:
      name: Soverom
    0a520802060100ff0e0269: # 1 06
      name: Bad
      data_type: 
        - Humidity
        - Temperature
    0a520800070100d2140269:
      name: Stue
      data_type: 
        - Humidity
        - Temperature
    0a5208980a0100d5310169:
      name: Utepotte
      data_type: 
        - Humidity
    08500902cbff017469:
      name: Steketermometer

- platform: yr
  monitored_conditions:
    - symbol
    - precipitation
    - temperature
    - lowClouds
    - mediumClouds

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone2/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Alarm'
      value_template: '{% if states.input_slider.alarmhour.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_slider.alarmhour.state|round(0)|string }}:{% if states.input_slider.alarmminutes.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_slider.alarmminutes.state|round(0)|string }}'
      entity_id: 
       - input_slider.alarmminutes
       - input_slider.alarmhour
    relative_alarm_time:
      value_template: '{{ states.input_slider.alarmhour.state|float|multiply(60) + states.input_slider.alarmminutes.state|float - (now().hour|float|multiply(60) + now().minute)}}'
      unit_of_measurement: "min"
      entity_id: 
       - sensor.time
    phone_battery:
      friendly_name: 'Telefon batteri'
      value_template: '{{ states.device_tracker.daniel.attributes.battery|float }}'
      unit_of_measurement: "%"
      entity_id: 
       - device_tracker.daniel
    target_temp_stue:
      value_template: '{{ states.climate.termostat_stue.attributes.temperature }}'
      entity_id: 
       - climate.termostat_stue
    mean_lux:
      friendly_name: 'Avg lux'
      value_template: >
                      {% set sum = 0 %}
                      {% set num = 0 %}
                      {% for state in [states.sensor.blomst_bokhylle_light_intensity, states.sensor.blomst_sofa_light_intensity, states.sensor.blomst_tv_light_intensity] %}
                          {%- if  as_timestamp(now()) - as_timestamp(state.last_updated) < 1800 -%}
                              {% set sum = sum + state.state|float %}
                              {% set num = num + 1|float %}
                          {%- endif %}
                          {%- if loop.last %}
                              {%- if  num > 0  -%}
                              {{ sum/num }}
                              {%- else -%}
                                  None
                              {%- endif %}
                          {%- endif %}
                      {%- endfor -%}
      unit_of_measurement: "lux"
      entity_id: 
       - sensor.blomst_bokhylle_light_intensity
       - sensor.blomst_sofa_light_intensity
       - sensor.blomst_tv_light_intensity
    mean_stue_temp:
      friendly_name: 'Avg stue temp'
      value_template: >
                      {% set sum = 0 %}
                      {% set num = 0 %}
                      {% for state in [states.sensor.blomst_tv_temperature, states.sensor.blomst_sofa_temperature, states.sensor.blomst_bokhylle_temperature, states.sensor.stue_temperature, states.sensor.stue_tvbenk_temperature] %}
                          {%- if  as_timestamp(now()) - as_timestamp(state.last_updated) < 300  and not (state.state == "unknown")-%}
                              {% set sum = sum + state.state|float %}
                              {% set num = num + 1|float %}
                          {%- endif %}
                          {%- if loop.last %}
                              {%- if  num > 0  -%}
                              {{ (sum/num) | round(1) }}
                              {%- else -%}
                               {{   states.sensor.stue_temperature.state }}
                              {%- endif %}
                          {%- endif %}
                      {%- endfor -%}
      unit_of_measurement: "°C"
      entity_id: 
       - sensor.blomst_tv_temperature
       - sensor.blomst_sofa_temperature
       - sensor.blomst_bokhylle_temperature
       - sensor.stue_temperature
       - sensor.stue_tvbenk_temperature
    no_updates:
      friendly_name: 'No updates'
      value_template: >
          {% set val = "" %}
          {% for state in states.sensor%}
                 {%- if  as_timestamp(now()) - as_timestamp(state.last_updated) > 60*60*10-%}
                    {% set val = val + state.entity_id + "\n"  %}
                 {%- endif %}
                 {%- if loop.last %}
                         {%- if  val == ""  -%}
                               {{ False }}
                         {%- else -%}
                               {{ val }}
                         {%- endif %} 
                  {%- endif %}
          {%- endfor-%}

- platform: time_date
  display_options:
    - 'time'

- platform: broadlink
  update_interval: 160
  host: 192.168.1.173
  mac: 'B4:43:0D:D1:02:F7'
  name: "Stue_tvbenk"
  timeout: 10
  monitored_conditions:
    - temperature
    - humidity
    - air_quality
    - light
    - noise

- platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

# platform: tellstick
# 11: Kjoleskap
# 22: Blomst_stue
# 41: Ute_veranda
# 31: Ute_soverom
# 52: Soverom
# 61: Bad
# 71: Stue
# only_named: 1
# temperature_scale: °C
# datatype_mask: 127
