- platform: rfxtrx
  automatic_add: False
  devices:
    0a52080601010038480349:
      name: Kjoleskap
    0a520806020100c7340159: # 02
      name: Stue_Vindu
    0a52080103010012260259:
      name: Ute_soverom
    0a5208030401001f1d0259:
      name: Ute_veranda
    0a52080705020095220269:
      name: Soverom
    0a520802060100ff0e0269: # 1 06
      name: Bad
      data_type: 
        - Humidity
        - Temperature
    0a520800070100d2140269:
      name: Stue
      data_type: 
        - Humidity
        - Temperature
    0a5208980a0100d5310169:
      name: Utepotte
      data_type: 
        - Humidity
    08500902cbff017469:
      name: Steketermometer

- platform: yr
  monitored_conditions:
    - symbol
    - precipitation
    - temperature
    - lowClouds
    - mediumClouds

- platform: xiaomi_scale
  mac: 'c8:0f:10:a1:4d:18'
  name: Vekt

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone2/temp"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: template
  sensors:
    relative_alarm_time:
      value_template: >
                     {% set relative_time =  (states.input_slider.alarmhour.state|float|multiply(60) + states.input_slider.alarmminutes.state|float) - (now().hour|float|multiply(60) + now().minute) %}
                     {%- if relative_time < 0 -%}
                        {{24*60+relative_time}}
                      {%- else -%}
                        {{relative_time}}
                     {%- endif %}
      unit_of_measurement: "min"
      entity_id: 
       - sensor.time
    phone_battery:
      friendly_name: 'Telefon batteri'
      value_template: '{{ states.device_tracker.daniel.attributes.battery|float }}'
      unit_of_measurement: "%"
      entity_id: 
       - device_tracker.daniel
    target_temp_stue:
      value_template: '{{ states.climate.termostat_stue.attributes.temperature }}'
      entity_id: 
       - climate.termostat_stue
    mean_lux:
      friendly_name: 'Avg lux'
      value_template: >
                      {% set sum = 0 %}
                      {% set num = 0 %}
                      {% for state in [states.sensor.blomst_bokhylle_light_intensity, states.sensor.blomst_sofa_light_intensity, states.sensor.blomst_tv_light_intensity] %}
                          {%- if  as_timestamp(now()) - as_timestamp(state.last_updated) < 1800 -%}
                              {% set sum = sum + state.state|float %}
                              {% set num = num + 1|float %}
                          {%- endif %}
                          {%- if loop.last %}
                              {%- if  num > 0  -%}
                              {{ sum/num }}
                              {%- else -%}
                                  None
                              {%- endif %}
                          {%- endif %}
                      {%- endfor -%}
      unit_of_measurement: "lux"
      entity_id: 
       - sensor.blomst_bokhylle_light_intensity
       - sensor.blomst_sofa_light_intensity
       - sensor.blomst_tv_light_intensity
    mean_stue_temp:
      friendly_name: 'Avg stue temp'
      value_template: >
                      {% set sum = 0 %}
                      {% set num = 0 %}
                      {% for state in [states.sensor.blomst_tv_temperature, states.sensor.blomst_sofa_temperature, states.sensor.blomst_bokhylle_temperature, states.sensor.stue_temperature, states.sensor.stue_tvbenk_temperature, states.sensor.temperature_158d000159c9d0, states.sensor.stue_bokhylle_temperature] %}
                          {%- if  state != None and as_timestamp(now()) - as_timestamp(state.last_updated) < 300 -%}
                              {% set sum = sum + state.state|float %}
                              {% set num = num + 1|float %}
                          {%- endif %}
                          {%- if loop.last %}
                              {%- if  states.sensor.stue_temperature != None and states.sensor.temperature_158d000159c9d0 != None and (as_timestamp(now()) - as_timestamp(states.sensor.stue_temperature.last_updated) < 180) and as_timestamp(now()) - as_timestamp(states.sensor.temperature_158d000159c9d0.last_updated) -%}
                               {{   ((states.sensor.stue_temperature.state|float + states.sensor.temperature_158d000159c9d0.state|float)/2.0) | round(1)}}
                              {%- elif   states.sensor.temperature_158d000159c9d0 != None and as_timestamp(now()) - as_timestamp(states.sensor.temperature_158d000159c9d0.last_updated) < 180 -%}
                               {{   states.sensor.temperature_158d000159c9d0.state  | round(1) }}
                              {%- elif   states.sensor.stue_temperature != None and  as_timestamp(now()) - as_timestamp(states.sensor.stue_temperature.last_updated) < 240 -%}
                               {{   states.sensor.stue_temperature.state }}
                              {%- elif  num > 0  -%}
                              {{ (sum/num) | round(1) }}
                              {%- else -%}
                               {{   states.sensor.stue_temperature.state }}
                              {%- endif %}
                          {%- endif %}
                      {%- endfor -%}
      unit_of_measurement: "째C"
      entity_id: 
       - sensor.temperature_158d000159c9d0
       - sensor.blomst_tv_temperature
       - sensor.blomst_sofa_temperature
       - sensor.blomst_bokhylle_temperature
       - sensor.stue_temperature
       - sensor.stue_tvbenk_temperature
    mean_bad_fuktighet:
      friendly_name: 'Bad fuktighet'
      value_template: >
                      {%- if  states.sensor.bad_humidity != None and states.sensor.humidity_158d000159f1af != None and (as_timestamp(now()) - as_timestamp(states.sensor.bad_humidity.last_updated) < 180) and as_timestamp(now()) - as_timestamp(states.sensor.humidity_158d000159f1af.last_updated) -%}
                                             {{   ((states.sensor.bad_humidity.state|float + states.sensor.humidity_158d000159f1af.state|float)/2.0) | round(1)}}
                      {%- elif   states.sensor.humidity_158d000159f1af != None and as_timestamp(now()) - as_timestamp(states.sensor.humidity_158d000159f1af.last_updated) < 180 -%}
                                             {{   states.sensor.humidity_158d000159f1af.state|float| round(1) }}
                      {%- else -%}
                                             {{   states.sensor.bad_humidity.state|float| round(1) }}
                      {%- endif %}
      unit_of_measurement: "%"
      entity_id: 
       - sensor.humidity_158d000159f1af
       - sensor.bad_humidity
    mean_bad_temp:
      friendly_name: 'Bad temperatur'
      value_template: >
                      {%- if  states.sensor.bad_temperature != None and states.sensor.temperature_158d000159f1af != None and (as_timestamp(now()) - as_timestamp(states.sensor.bad_temperature.last_updated) < 180) and as_timestamp(now()) - as_timestamp(states.sensor.temperature_158d000159f1af.last_updated) -%}
                                             {{   ((states.sensor.bad_temperature.state|float + states.sensor.temperature_158d000159f1af.state|float)/2.0) | round(1)}}
                      {%- elif   states.sensor.temperature_158d000159f1af != None and as_timestamp(now()) - as_timestamp(states.sensor.temperature_158d000159f1af.last_updated) < 180 -%}
                                             {{   states.sensor.temperature_158d000159f1af.state|float| round(1) }}
                      {%- else -%}
                                             {{   states.sensor.bad_temperature.state|float| round(1) }}
                      {%- endif %}
      unit_of_measurement: "째C"
      entity_id: 
       - sensor.temperature_158d000159f1af
       - sensor.bad_temperature
#    no_updates:
#      friendly_name: 'No updates'
#      value_template: >
#          {% set val = "" %}
#          {% for state in states.sensor%}
#                 {%- if  as_timestamp(now()) - as_timestamp(state.last_updated) > 60*60*10-%}
#                    {% set val = val + state.entity_id + "\n"  %}
#                 {%- endif %}
#                 {%- if loop.last %}
#                         {%- if  val == ""  -%}
#                               {{ False }}
#                         {%- else -%}
#                               {{ val }}
#                         {%- endif %} 
#                  {%- endif %}
#          {%- endfor-%}


- platform: time_date
  display_options:
    - 'time'

- platform: broadlink
  update_interval: 160
  host: 192.168.1.173
  mac: 'B4:43:0D:D1:02:F7'
  name: "Stue_tvbenk"
  timeout: 10
  monitored_conditions:
    - temperature
    - humidity
    - air_quality
    - light
    - noise

- platform: broadlink
  update_interval: 160
  host: 192.168.1.100
  mac: '34:EA:34:E4:6D:B0'
  name: "Stue_bokhylle"
  timeout: 10
  monitored_conditions:
    - temperature

- platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

- platform: brain_fm
  email: !secret email
  password: !secret brain_fm_password

# platform: tellstick
# 11: Kjoleskap
# 22: Blomst_stue
# 41: Ute_veranda
# 31: Ute_soverom
# 52: Soverom
# 61: Bad
# 71: Stue
# only_named: 1
# temperature_scale: 째C
# datatype_mask: 127

- platform: miflora
  mac: C4:7C:8D:61:7E:3B 
  name: Blomst tv
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

- platform: miflora
  mac: C4:7C:8D:61:7F:EC 
  name: Blomst sofa
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

- platform: miflora
  mac: C4:7C:8D:61:7E:5D 
  name: Blomst bokhylle
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery
