- platform: rfxtrx
  automatic_add: False
  devices:
    0a5208030401001f1d0259:
      name: Ute_veranda
    0a52080705020095220269:
      name: Stue
    0a5208450a0101e8160279:
      name: varmtvann
    0a5208020201019e230249:
      name: varmtvann_ut
    0a52080b070100eb230259:
      name: varmtvann_nede

- platform: yr
  monitored_conditions:
    - symbol
    - precipitation
    - temperature

#- platform: xiaomi_scale
#  mac: 'c8:0f:10:a1:4d:18'
#  name: Vekt
#- platform: scale

- platform: template
  sensors:
    relative_alarm_time:
      value_template: >
                     {% set relative_time =  (states.input_number.alarmhour.state|float|multiply(60) + states.input_number.alarmminutes.state|float) - (now().hour|float|multiply(60) + now().minute) %}
                     {%- if relative_time < 0 -%}
                        {{24*60+relative_time}}
                      {%- else -%}
                        {{relative_time}}
                     {%- endif %}
      unit_of_measurement: "min"
      entity_id: 
       - sensor.time
    phone_battery:
      friendly_name: 'Telefon batteri'
      value_template: '{{ states.device_tracker.daniel.attributes.battery|float }}'
      unit_of_measurement: "%"
      entity_id: 
       - device_tracker.daniel
    phone_speed:
      friendly_name: 'Telefon speed'
      value_template: '{{ states.device_tracker.daniel.attributes.speed|float }}'
      unit_of_measurement: " "
      entity_id: 
       - device_tracker.daniel
    phone_direction:
      friendly_name: 'Telefon direction'
      value_template: '{{ states.device_tracker.daniel.attributes.direction  }}'
      unit_of_measurement: ""
      entity_id: 
       - device_tracker.daniel
    phone_activity:
      friendly_name: 'Telefon activity'
      value_template: '{{ states.device_tracker.daniel.attributes.activity }}'
      unit_of_measurement: ""
      entity_id: 
       - device_tracker.daniel
    effekt_vaskemaskin:
      friendly_name: 'Effekt vaskemasin'
      value_template: '{{ states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power.state|float }}'
      unit_of_measurement: "W"
      entity_id: 
       - sensor.fibaro_system_fgwpef_wall_plug_gen5_power
    set_temp:
      value_template: '{{states.climate.stue.attributes.temperature|float }}'
      unit_of_measurement: "°C"
      entity_id: 
       - climate.stue
    max_tibber:
      friendly_name: "Max price"
      unit_of_measurement: 'kr'
      value_template: "{{states.sensor.electricity_price_hamretunet_10.attributes.max_price}}"
       
- platform: time_date
  display_options:
    - 'time'

- platform: brain_fm
  email: !secret email
  password: !secret brain_fm_password


- platform: tibber
  access_token: !secret tibber

#- platform: nordpool
#  currency: 'NOK'
#  region: 'Molde'
#  name: "Elspot kWh"

- platform: google_travel_time
  name: Phone To Home
  api_key: !secret google_api_key
  origin: device_tracker.daniel
  destination: zone.home
  options:
    mode: bicycling

- platform: google_travel_time
  name: Phone To home car
  api_key: !secret google_api_key
  origin: device_tracker.daniel
  destination: zone.home
  options:
    mode: driving

- platform: mqtt
  name: "Total effect"
  state_topic: "6970631400499129/effect/watt"
  value_template: "{{ float(value)/1000.0 }}"
  unit_of_measurement: "kW"
  
  
- platform: mqtt
  name: "Cumulative_hourly_reactive_import_energy"
  state_topic: "6970631400499129/Cumulative_hourly_reactive_import_energy/wh"
  value_template: "{{ value }}"
  unit_of_measurement: "Wh"
  
  
- platform: mqtt
  name: "Cumulative_hourly_active_import_energy"
  state_topic: "6970631400499129/Cumulative_hourly_active_import_energy/wh"
  value_template: "{{ float(value) /1000.0 }}"
  unit_of_measurement: "kWh"
  
- platform: mqtt
  name: "Diff_cumulative_hourly_active_import_energy"
  state_topic: "6970631400499129/Diff_cumulative_hourly_active_import_energy/wh"
  value_template: "{{ float(value) /1000.0 }}"
  unit_of_measurement: "kWh"
 
- platform: mqtt
  name: "Houtly_cons"
  state_topic: "6970631400499129/hourly_cons/ws"
  value_template: "{{ float(value) /3600000.0 }}"
  unit_of_measurement: "kWh"


- platform: filter
  name: "filtered total effect"
  entity_id: sensor.total_effect
  filters:
   - filter: time_simple_moving_average
     window_size: 00:30
     precision: 2
