- platform: rfxtrx
  automatic_add: False
  signal_repetitions: 2
  devices:
    0b1100cd0213c7f210010f70:
      name: Movement1
      fire_event: True
    0b11000a02ef9ff210010f50:
      name: Movement2
    0b1100000213b3f210010f70:
      name: Movement_do
      fire_event: True
    09130000db153a012670:
      name: Movement_soverom
      fire_event: True
    0913009c94597a013670:
      name: Movement_soverom_seng
      fire_event: True
    0913002355997a013d60:
      name: Movement_kjokken
      fire_event: True
    091300122ebf8a013670:
      name: Movement_stue
      fire_event: True
    0b1100e003af16aa10000060:
      name: Door
      fire_event: True
    0b110053026cfeaa10010f70:
      name: Door_bad
      fire_event: True
    0b11000300932eaa10000060:
      name: door_bedroom
      fire_event: True
    0b11001d00c9277801010f70: 
      name: ovn_soverom
    0b11001901f973ca01010f70: 
      name: ovn_stue
    0b110086035f46aa10000050:
      name: door_do
      fire_event: True      
    09130006545503020e60:
      name: leggetid
      fire_event: True
    0b11005b0154b55e01040f60:
      name: leggetid_stue
      fire_event: True
    0913000e9da2da015270:
      name: Movement3
      fire_event: True
    0b11000d00e6ce760d010f60:
      name: soverom_switch1
      fire_event: True
    09130004d55555019870:
      name: stovsuger_running
      fire_event: True
    09130009d744fc01a870:
      name: lyd_soverom
      fire_event: True
    0b11003d0097251e01040f50:
      name: main
      fire_event: True
    0b110002012c299a0a000070:
      name: lux
      fire_event: True    
    09130051aebf8a013640:
      name: vann_bad
      fire_event: True    
    091300381cd55001f670:
      name: vann_kjokken
      fire_event: True
    0913001587a768022e60:
      name: news_soverom
      fire_event: True
    09130033154c02011d70:
      name: knapp
      fire_event: True

#- platform: command_line
#  switches:
#    stovsuger:
#      oncmd:  "python /home/dahoiv/.homeassistant/orvibo/orvibo.py -i 192.168.1.18 -e /home/dahoiv/.homeassistant/orvibo/start_stovsuger.ir"
#      offcmd: "python /home/dahoiv/.homeassistant/orvibo/orvibo.py -i 192.168.1.18 -e /home/dahoiv/.homeassistant/orvibo/stop_stovsuger.ir"

- platform: broadlink
  host: 192.168.1.243
  mac: 'B4:43:0D:CC:0F:57'
  timeout: 15
  switches:
    tv:
      friendly_name: "Tv"
      command_on:  'JgAcAB0dHB44HhweGx4cHR06HB0cHhwdHB8bHhwADQUAAAAAAAAAAAAAAAA='
      command_off: 'JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA='
    stovsuger:
      friendly_name: "Stovsuger"
      command_on:  'JgBIAAABJpMSOBITEhMSExITEhMSExITFw4SNxI4EjcSOBI4ETgSOBITEhMSNxITEhMSExITEhMSOBI3EhMSOBI4ETgSOBI3EgANBQ=='
      command_off: 'JgBQAAABJpMTNhITEhMSExITEhQRExITEhMSOBI4ETgSOBI3FDYSOBETFDYUNhMSEhMSExITExISNxQREhMSOBM2EjgSOBE4EgAFEAABJUoSAA0FAAAAAAAAAAA='
    lydplanke:
      friendly_name: "lydplanke"
      command_on:  'JgAoAFgcDh4NEA4PLCwNEA0QHB4ODw4QDRANEA4NEBANEBwODx4NEA4ADQU='
      command_off: 'JgAoAFgcDh4NEA4PLCwNEA0QHB4ODw4QDRANEA4NEBANEBwODx4NEA4ADQU=
'
    lydplanke_aux:
      friendly_name: "lydplanke aux"
      command_on: 'JgAoAFYeDh4NEA4PKy0NEA0QHB4OEA0QDRANEA4PHBAODw4eDRAODw4ADQU=
'

