# https://www.nrk.no/mp3aac/
- alias: 'Radio stue'
  trigger:
    platform: state
    entity_id: input_select.radio_stue
  action:
   - service: media_player.play_media
     entity_id: media_player.stue_kjokken
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_stue', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_stue', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_stue', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% elif is_state('input_select.radio_stue', 'P2') %}
               http://nrk-mms-live.online.no/nrk_radio_p2_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Auto radio stue"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.stue_kjokken
     to: 'idle'
     for:
       seconds: 3
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_stue
    - service: input_select.select_option
      entity_id: input_select.radio_stue
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_stue

- alias: "P2 stue"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: flip90
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') or is_state('media_player.stue_kjokken', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: homeassistant.turn_off
      entity_id: switch.google_music
    - service: media_player.turn_on
      entity_id: media_player.stue_kjokken
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue_kjokken
        volume_level: 0.23
    - service: input_select.select_option
      entity_id: input_select.radio_stue
      data:
        option: "P2"
    - service: automation.trigger
      entity_id: automation.radio_stue

- alias: "Endre radiokanal stue"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: flip90
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') or is_state('media_player.stue_kjokken', 'playing') %}
          true
        {% else %}
          false
        {% endif %}
  action:
  - service: homeassistant.turn_off
    entity_id: switch.google_music
  - service: input_select.select_next
    entity_id: input_select.radio_stue

- alias: "Nyheter stue"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d0001118a8a
       action_type: shake_air
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') or is_state('media_player.stue_kjokken', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.turn_on
      entity_id: media_player.stue
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue_kjokken
        volume_level: 0.23
    - service: news.read_news
      entity_id: media_player.stue_kjokken
    - service: homeassistant.turn_on
      entity_id: automation.auto_radio_stue

- alias: "Nyheter stue stop"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d0001118a8a
       action_type: shake_air
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') or is_state('media_player.stue_kjokken', 'playing') %}
          true
        {% else %}
          false
        {% endif %}
  action:
    - service: homeassistant.turn_off
      entity_id: switch.google_music
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_stue
    - service: media_player.turn_off
      entity_id: media_player.stue_kjokken

- alias: "Cube i fritt fall, stue"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: free_fall
  action:
  - service: media_player.turn_on
    entity_id: media_player.stue
  - service: media_player.volume_set
    data:
      entity_id: media_player.stue_kjokken
      volume_level: 0.23
  - service: tts.google_say
    entity_id: media_player.stue_kjokken
    data_template:
      message: 'Au, au. Vær litt forsiktig da.'
      cache: true

- alias: "Volum stue"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
        entity_id: binary_sensor.cube_158d0001118a8a
        action_type: rotate
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.stue_kjokken
        volume_level: >
                      {% set state = states.media_player.stue_kjokken.attributes.volume_level + (trigger.event.data.action_value|float)/90 -%}
                      {%-  if state > 1 -%}
                         {%- set state  = 1 -%}
                      {%-  elif state < 0 -%}
                         {%- set state  = 0 -%}
                      {%- endif %}
                      {{ state }}
- alias: "Gmusic stue"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: tap_twice
  action:
   - service: homeassistant.turn_off
     entity_id: switch.google_music
   - service: input_select.select_option
     entity_id: input_select.media_player
     data:
       option: "stue"
   - service: input_select.select_next
     entity_id: input_select.music
   - service: homeassistant.turn_on
     entity_id: switch.google_music




# SOVEROM


- alias: "Radio soverom av"
  trigger:
   - platform: state
     entity_id: input_select.radio_soverom
     to: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.soverom

# https://www.nrk.no/mp3aac/
- alias: 'Radio soverom'
  trigger:
    platform: state
    entity_id: input_select.radio_soverom
  action:
   - service: media_player.play_media
     entity_id: media_player.soverom
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_soverom', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_soverom', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_soverom', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% elif is_state('input_select.radio_bad', 'P2') %}
               http://nrk-mms-live.online.no/nrk_radio_p2_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Nyheter soverom"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: double
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.soverom', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.soverom
        volume_level: 0.55
    - service: news.read_news
      data:
        message_type: "1"
        entity_id: media_player.soverom
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: automation.auto_radio_soverom

- alias: "Nyheter soverom stop"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: double
  condition:
   - condition: state
     entity_id: media_player.soverom
     state: 'playing'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_soverom
    - service: media_player.turn_off
      entity_id: media_player.soverom



#GENERELT


- alias: "Radio av"
  trigger:
   - platform: state
     entity_id: input_select.radio
     to: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.hele_huset

# https://www.nrk.no/mp3aac/
- alias: 'Radio'
  trigger:
    platform: state
    entity_id: input_select.radio
  action:
   - service: media_player.play_media
     entity_id: media_player.hele_huset
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% elif is_state('input_select.radio_bad', 'P2') %}
               http://nrk-mms-live.online.no/nrk_radio_p2_mp3_h
           {% endif %}
       media_content_type: audio/mp3
   - service: media_player.volume_set
     data:
       entity_id: media_player.hele_huset
       volume_level: 0.23
