- alias: "Nyheter hjemkomst"
  trigger:
   - platform: state
     entity_id: group.tracker
     from: 'not_home'
     to: 'home'
  action:
    - service: homeassistant.turn_on
      data: 
        entity_id: automation.nyheter_hjemkomst_start

- alias: "Nyheter hjemkomst start"
  initial_state: False
  trigger:
    - platform: state
      entity_id: binary_sensor.door, binary_sensor.door_do, binary_sensor.door_soverom, binary_sensor.movement1,  binary_sensor.movement2, binary_sensor.movement3, binary_sensor.movement_do
      state: 'on'
  condition:
    - condition: template
      value_template: '{% if states.automation.nyheter_hjemkomst_start.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.nyheter_hjemkomst_start.attributes.last_triggered)) > 1800 }}  {% else %}  true {% endif %}'
  action:
    - service: media_player.turn_off
      entity_id: media_player.chromecast1877
    - service: homeassistant.turn_off
      data: 
        entity_id: automation.nyheter_hjemkomst_start
    - service: homeassistant.turn_off
      entity_id: switch.tv
    - delay: '00:00:03'
    - service: homeassistant.turn_on
      entity_id: switch.tv
    - delay: '00:00:10'
    - service: news.read_news
      data:
        message_type: "0"
        entity_id: media_player.chromecast1877
    - service: homeassistant.turn_on
      entity_id: automation.turn_off_tv_after_news

- alias: "Nyheter stua"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.news_stue', 'state': 'unknown command (0x87a768)'}
  action:
   - service: homeassistant.turn_on
     entity_id: switch.tv
   - service: news.read_news
     data:
       entity_id: media_player.chromecast1877

- alias: "Turn off tv after news"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.chromecast1877
     state: 'idle'
     for:
       seconds: 1
  action:
   - service: homeassistant.turn_off
     entity_id: switch.tv
   - service: homeassistant.turn_off
     entity_id: automation.turn_off_tv_after_news




- alias: "Radio bad av"
  trigger:
   - platform: state
     entity_id: input_select.radio_bad
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.bad

# https://www.nrk.no/mp3aac/
- alias: 'Radio bad'
  trigger:
    platform: state
    entity_id: input_select.radio_bad
  action:
   - service: homeassistant.turn_on
     entity_id: switch.tv
   - service: media_player.play_media
     entity_id: media_player.bad
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_bad', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_bad', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_bad', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Auto radio bad"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.bad
     state: 'idle'
     for:
       seconds: 5
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: automation.auto_radio_bad
    - service: input_select.select_option
      entity_id: input_select.radio_bad
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_bad

- alias: "Endre radiokanal baderom"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000xxxxxc2
      action_type: flip90
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000xxxxxc2
      action_type: flip180
  action:
  - service: input_select.select_next
    entity_id: input_select.radio_bad

- alias: "Nyheter bad"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d000xxxxxc2
       action_type: shake_air
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.bad', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: news.read_news
      data:
        entity_id: media_player.bad
    - service: homeassistant.turn_on
      data: 
        entity_id: automation.auto_radio_bad

- alias: "Nyheter bad stop"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d000xxxxxc2
       action_type: shake_air
  condition:
   - condition: state
     entity_id: media_player.bad
     state: 'playing'
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: automation.auto_radio_bad

- alias: "Cube i fritt fall"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000xxxxxc2
      action_type: free_fall
  action:
  - service: tts.google_say
    entity_id: media_player.bad
    data_template:
      message: 'Au, au. Vær litt forsiktig da.'
      cache: false



- alias: "Radio stue av"
  trigger:
   - platform: state
     entity_id: input_select.radio_stue
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.chromecast1877
   - service: homeassistant.turn_off
     entity_id: switch.tv

# https://www.nrk.no/mp3aac/
- alias: 'Radio stue'
  trigger:
    platform: state
    entity_id: input_select.radio_stue
  action:
   - service: homeassistant.turn_on
     entity_id: switch.tv
   - service: media_player.play_media
     entity_id: media_player.chromecast1877
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_stue', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_stue', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_stue', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3



- alias: "Radio soverom av"
  trigger:
   - platform: state
     entity_id: input_select.radio_soverom
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.soverom

# https://www.nrk.no/mp3aac/
- alias: 'Radio soverom'
  trigger:
    platform: state
    entity_id: input_select.radio_soverom
  action:
   - service: media_player.play_media
     entity_id: media_player.soverom
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_soverom', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_soverom', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_soverom', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Nyheter soverom"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.news_soverom', 'state': 'unknown command (0x87a768)'}
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.soverom', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: homeassistant.turn_on
      entity_id: script.news_soverom
    - service: homeassistant.turn_on
      entity_id: automation.auto_radio_soverom

- alias: "Nyheter soverom stop"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.news_soverom', 'state': 'unknown command (0x87a768)'}
  condition:
   - condition: state
     entity_id: media_player.soverom
     state: 'playing'
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: automation.auto_radio_soverom






- alias: "Radio av"
  trigger:
   - platform: state
     entity_id: input_select.radio
     state: 'Av'
  action:
   - service: media_player.turn_off
     #entity_id: media_player.chromecast1877, media_player.bad, media_player.soverom

# https://www.nrk.no/mp3aac/
- alias: 'Radio'
  trigger:
    platform: state
    entity_id: input_select.radio
  action:
   - service: media_player.play_media
     #entity_id: media_player.chromecast1877, media_player.bad, media_player.soverom
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3

