# STUE

- alias: "Nyheter hjemkomst"
  trigger:
   - platform: state
     entity_id: group.tracker
     from: 'not_home'
     to: 'home'
  action:
    - service: media_player.turn_on
      entity_id: media_player.stue
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue
        volume_level: 0.65
    - service: homeassistant.turn_on
      entity_id: automation.nyheter_hjemkomst_start

- alias: "Nyheter hjemkomst start"
  initial_state: False
  trigger:
    - platform: state
      entity_id: binary_sensor.door, binary_sensor.door_do, binary_sensor.door_soverom, binary_sensor.movement1,  binary_sensor.movement2, binary_sensor.movement3, binary_sensor.movement_do
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: automation.nyheter_hjemkomst_start
    - condition: and
      conditions:
      - condition: template
        value_template: '{% if states.automation.nyheter_hjemkomst_start.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.nyheter_hjemkomst_start.attributes.last_triggered)) > 1800 }}  {% else %}  true {% endif %}'
      - condition: template
        value_template: '{% if states.automation.nyheter_hjemkomst.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.nyheter_hjemkomst.attributes.last_triggered)) < 900 }}  {% else %}  false {% endif %}'

    - delay: '00:00:15'
    - service: news.read_news
      data:
        message_type: "0"
        entity_id: media_player.stue

- alias: "Nyheter stue, knapp"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.news_stue', 'state': 'unknown command (0x87a768)'}
  action:
   - service: news.read_news
     entity_id: media_player.stue

- alias: "Radio stue av"
  trigger:
   - platform: state
     entity_id: input_select.radio_stue
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.stue

# https://www.nrk.no/mp3aac/
- alias: 'Radio stue'
  trigger:
    platform: state
    entity_id: input_select.radio_stue
  action:
   - service: media_player.play_media
     entity_id: media_player.stue
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_stue', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_stue', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_stue', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Auto radio stue"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.stue
     state: 'idle'
     for:
       seconds: 5
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_stue
    - service: input_select.select_option
      entity_id: input_select.radio_stue
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_stue

- alias: "P3 stue"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: flip90
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.turn_on
      entity_id: media_player.stue
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue
        volume_level: 0.23
    - service: input_select.select_option
      entity_id: input_select.radio_stue
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_stue

- alias: "Endre radiokanal stue"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: flip90
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') %}
          true
        {% else %}
          false
        {% endif %}
  action:
  - service: input_select.select_next
    entity_id: input_select.radio_stue

- alias: "Nyheter stue"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d0001118a8a
       action_type: shake_air
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.stue', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.turn_on
      entity_id: media_player.stue
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue
        volume_level: 0.23
    - service: news.read_news
      entity_id: media_player.stue
    - service: homeassistant.turn_on
      entity_id: automation.auto_radio_stue

- alias: "Nyheter stue stop"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d0001118a8a
       action_type: shake_air
  condition:
   - condition: state
     entity_id: media_player.stue
     state: 'playing'
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: automation.auto_radio_stue
    - service: media_player.turn_off
      entity_id: media_player.stue

- alias: "Cube i fritt fall, stue"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001118a8a
      action_type: free_fall
  action:
  - service: media_player.turn_on
    entity_id: media_player.stue
  - service: media_player.volume_set
    data:
      entity_id: media_player.stue
      volume_level: 0.23
  - service: tts.google_say
    entity_id: media_player.stue
    data_template:
      message: 'Au, au. Vær litt forsiktig da.'
      cache: true

- alias: "Volum stue"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
        entity_id: binary_sensor.cube_158d0001118a8a
        action_type: rotate
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.stue
        volume_level: >
                      {% set state = states.media_player.stue.attributes.volume_level + (trigger.event.data.action_value|float)/90 -%}
                      {%-  if state > 1 -%}
                         {%- set state  = 1 -%}
                      {%-  elif state < 0 -%}
                         {%- set state  = 0 -%}
                      {%- endif %}
                      {{ state }}

- alias: "Start media stue"
  trigger:
   - platform: state
     entity_id: binary_sensor.state_mediaplayer_stue
     state: 'on'
   - platform: state
     entity_id: media_player.stue
     from: "off"
     to : "idle"
  action:
   - service: homeassistant.turn_off
     entity_id: automation.start_media_stue
   - service: homeassistant.turn_on
     entity_id: switch.lydplanke
    # retry if failed

- alias: "Stop media stue"
  trigger:
   - platform: state
     entity_id: binary_sensor.state_mediaplayer_stue
     state: 'off'
     for:
       minutes: 16
  action:
   - service: homeassistant.turn_on
     entity_id: automation.start_media_stue


# BAD



- alias: "Radio bad av"
  trigger:
   - platform: state
     entity_id: input_select.radio_bad
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.bad

# https://www.nrk.no/mp3aac/
- alias: 'Radio bad'
  trigger:
    platform: state
    entity_id: input_select.radio_bad
  action:
   - service: media_player.play_media
     entity_id: media_player.bad
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_bad', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_bad', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_bad', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Auto radio bad"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.bad
     state: 'idle'
     for:
       seconds: 5
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_bad
    - service: input_select.select_option
      entity_id: input_select.radio_bad
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_bad

- alias: "P3 bad"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001182e4f
      action_type: flip90
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.bad', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.turn_on
      entity_id: media_player.bad
    - service: media_player.volume_set
      data:
        entity_id: media_player.bad
        volume_level: 0.4
    - service: input_select.select_option
      entity_id: input_select.radio_bad
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_bad

- alias: "Endre radiokanal baderom"
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001182e4f
      action_type: flip90
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.bad', 'playing') %}
          true
        {% else %}
          false
        {% endif %}
  action:
  - service: input_select.select_next
    entity_id: input_select.radio_bad

- alias: "Nyheter bad"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d0001182e4f
       action_type: shake_air
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.bad', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.turn_on
      entity_id: media_player.bad
    - service: media_player.volume_set
      data:
        entity_id: media_player.bad
        volume_level: 0.4
    - service: news.read_news
      entity_id: media_player.bad
    - service: homeassistant.turn_on
      entity_id: automation.auto_radio_bad

- alias: "Nyheter bad stop"
  trigger:
   - platform: event
     event_type: cube_action
     event_data:
       entity_id: binary_sensor.cube_158d0001182e4f
       action_type: shake_air
  condition:
   - condition: state
     entity_id: media_player.bad
     state: 'playing'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_bad
    - service: media_player.turn_off
      entity_id: media_player.bad

- alias: "Cube i fritt fall, bad"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001182e4f
      action_type: free_fall
  action:
  - service: media_player.turn_on
    entity_id: media_player.bad
  - service: media_player.volume_set
    data:
      entity_id: media_player.bad
      volume_level: 0.4
  - service: tts.google_say
    entity_id: media_player.bad
    data_template:
      message: 'Au, au. Vær litt forsiktig da.'
      cache: true

- alias: "Volum bad"
  trigger:
    platform: event
    event_type: cube_action
    event_data:
        entity_id: binary_sensor.cube_158d0001182e4f
        action_type: rotate
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.bad
        volume_level: >
                      {% set state = states.media_player.bad.attributes.volume_level + (trigger.event.data.action_value|float)/90 -%}
                      {%-  if state > 1 -%}
                         {%- set state  = 1 -%}
                      {%-  elif state < 0 -%}
                         {%- set state  = 0 -%}
                      {%- endif %}
                      {{ state }}





# SOVEROM


- alias: "Radio soverom av"
  trigger:
   - platform: state
     entity_id: input_select.radio_soverom
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.soverom

# https://www.nrk.no/mp3aac/
- alias: 'Radio soverom'
  trigger:
    platform: state
    entity_id: input_select.radio_soverom
  action:
   - service: media_player.play_media
     entity_id: media_player.soverom
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio_soverom', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio_soverom', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio_soverom', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3

- alias: "Nyheter soverom"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: hold
  condition:
    - condition: template
      value_template: >
        {% if is_state('media_player.soverom', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.soverom
        volume_level: 0.55
    - service: news.read_news
      data:
        message_type: "1"
        entity_id: media_player.soverom
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: automation.auto_radio_soverom

- alias: "Nyheter soverom stop"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: hold
  condition:
   - condition: state
     entity_id: media_player.soverom
     state: 'playing'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_soverom
    - service: media_player.turn_off
      entity_id: media_player.soverom



#GENERELT


- alias: "Radio av"
  trigger:
   - platform: state
     entity_id: input_select.radio
     state: 'Av'
  action:
   - service: media_player.turn_off
     entity_id: media_player.hele_huset

# https://www.nrk.no/mp3aac/
- alias: 'Radio'
  trigger:
    platform: state
    entity_id: input_select.radio
  action:
   - service: media_player.play_media
     entity_id: media_player.hele_huset
     data_template:
       media_content_id: >-
           {% if is_state('input_select.radio', 'Alltid Nyheter') %}
               http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h
           {% elif is_state('input_select.radio', 'P1') %}
               http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h
           {% elif is_state('input_select.radio', 'P3') %}
               http://nrk-mms-live.online.no/nrk_radio_p3_mp3_h
           {% endif %}
       media_content_type: audio/mp3
   - service: media_player.volume_set
     data:
       entity_id: media_player.hele_huset
       volume_level: 0.23
