- alias: "Baderom fuktighet"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bad'}
  condition:
   - condition: numeric_state
     entity_id: sensor.bad_humidity
     above: 30
   - condition: template
     value_template: '{% if states.automation.baderom_fuktighet.attributes.last_triggered %} {{(as_timestamp(now())-as_timestamp(states.automation.baderom_fuktighet.attributes.last_triggered)) > 90 }}  {% else %}  true {% endif %}'
  action:
  - service: tts.google_say
    entity_id: media_player.bad
    data_template:
      message: 'Husk å skru på vifta, da luftfuktigheten er {{states.sensor.bad_humidity.state | float | round(0)}}.'
      cache: false

