- alias: "Lys gang timer"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.movement3', 'state': 'unknown command (0x9da2da)'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
  condition:
   - condition: state
     entity_id: script.stovsuger_running
     state: 'off'
     for:
       minutes: 1
  action:
    - service: script.turn_off
      data: 
        entity_id: script.timed_lys_gang
    - delay: '00:00:01'
    - service: script.turn_on
      data:
        entity_id: script.timed_lys_gang

- alias: "Lys gang dag"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.movement3', 'state': 'unknown command (0x9da2da)'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_do'}
  condition:
   - condition: template
     value_template: '{% if states.automation.lys_gang_dag.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.lys_gang_dag.attributes.last_triggered)) > 2 }}  {% else %}  true {% endif %}'
   - condition: state
     entity_id: script.stovsuger_running
     state: 'off'
     for:
       minutes: 1
   - condition: state
     entity_id: light.gang
     state: 'off'
   - condition: time
     after: '07:00:00'
     before: '22:00:00'     
  action:
   - service: homeassistant.turn_off
     entity_id: automation.lys_gang_dag
   - service: homeassistant.turn_on
     data:
       entity_id: light.gang
       brightness: 80
   - delay: '00:02:00'
   - service: homeassistant.turn_on
     entity_id: automation.lys_gang_dag


- alias: "Lys gang natt"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.movement3', 'state': 'unknown command (0x9da2da)'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
  condition:
   - condition: template
     value_template: '{% if states.automation.lys_gang_natt.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.lys_gang_natt.attributes.last_triggered)) > 2 }}  {% else %}  true {% endif %}'
   - condition: state
     entity_id: script.stovsuger_running
     state: 'off'
     for:
       minutes: 1
   - condition: state
     entity_id: light.gang
     state: 'off'
   - condition: time
     before: '07:00:00'
     after: '22:00:00'     
  action:
   - service: homeassistant.turn_off
     entity_id: automation.lys_gang_dag
   - service: homeassistant.turn_on
     data:
       entity_id: light.gang
       rgb_color: [140,7,0]
   - delay: '00:02:00'
   - service: homeassistant.turn_on
     entity_id: automation.lys_gang_dag


- alias: "Lys do timer"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'binary_sensor.movement_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.movement3', 'state': 'unknown command (0x9da2da)'}
  action:
    - service: script.turn_off
      data: 
        entity_id: script.timed_lys_do
    - delay: '00:00:01'
    - service: script.turn_on
      data:
        entity_id: script.timed_lys_do

- alias: "Lys do dag"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'binary_sensor.movement_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_do'}
  condition:
   - condition: template
     value_template: '{% if states.automation.lys_do_dag.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.lys_do_dag.attributes.last_triggered)) > 2 }}  {% else %}  true {% endif %}'
   - condition: state
     entity_id: light.do
     state: 'off'
   - condition: time
     after: '07:00:00'
     before: '22:00:00'     
  action:
   - service: homeassistant.turn_on
     data:
       entity_id: light.do
       xy_color: [0.4607,0.43]
       
- alias: "Lys do natt"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'binary_sensor.movement_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_do'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
   - platform: event
     event_type: button_pressed
     event_data: {'entity_id': 'switch.movement3', 'state': 'unknown command (0x9da2da)'}
  condition:
   - condition: template
     value_template: '{% if states.automation.lys_do_natt.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.lys_do_natt.attributes.last_triggered)) > 2 }}  {% else %}  true {% endif %}'
   - condition: state
     entity_id: light.do
     state: 'off'
   - condition: time
     before: '07:00:00'
     after: '22:00:00'     
  action:
   - service: homeassistant.turn_on
     data:
       entity_id: light.do
       xy_color: [0.653,0.343]
