- alias: "Dark"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 5
    - platform: state
      entity_id: binary_sensor.stue_lux
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: group.tracker
      state: 'home'
    - condition: time
      after: '14:00:00'
      before: '23:00:00'
    - condition: state
      entity_id: script.light_turned_off_5min
      state: 'off'
  action:
     service: scene.turn_on
     entity_id: scene.Normal_lys

- alias: "Home"
  trigger:
    - platform: state
      entity_id: group.tracker
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: switch.movement1, switch.movement2, switch.movement2, switch.movement_do, binary_sensor.door_soverom, binary_sensor.door_do, switch.door
      state: 'on'
  condition:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 8
      - condition: state
        entity_id: binary_sensor.stue_lux
        state: 'off'
        for:
          minutes: 15
    - condition: state
      entity_id: light.Lys_stue
      state: 'off'
    - condition: state
      entity_id: light.Lys_TV
      state: 'off'
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
    - condition: state
      entity_id: script.light_turned_off_5min
      state: 'off'
    - condition: state
      entity_id: script.leggetid
      state: 'off'
      for:
        hours: 2
    - condition: or
      conditions:
      - condition: state
        entity_id: script.stovsuger_running
        state: 'off'
        for:
          minutes: 2
      - condition: state
        entity_id: group.tracker
        state: 'home'
  action:
      service: scene.turn_on
      entity_id: scene.Normal_lys

- alias: "Night"
  trigger:
    - platform: state
      entity_id: switch.movement1, switch.movement2, switch.movement2, switch.movement_do, binary_sensor.door_soverom, binary_sensor.door_do, switch.door
      state: 'on'
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 8
    - condition: or
      conditions:
      - condition: state
        entity_id: light.Lys_stue
        state: 'off'
      - condition: template
        value_template: '{{states.light.Lys_stue.attributes.brightness == 101}}'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.Lys_TV
        state: 'off'
      - condition: template
        value_template: '{{states.light.Lys_TV.attributes.brightness == 101}}'
    - condition: state
      entity_id: script.light_turned_off_5min
      state: 'off'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{(as_timestamp(now())-as_timestamp(states.script.leggetid_soverom.last_triggered)) < 60*60*2 }}'
      - condition: time
        after: '23:00:00'
        before: '07:00:00'
  action:
    # Cancel ev. old timers 
    - service: script.turn_off
      data: 
         entity_id: script.timed_lights_5min_off
    - service: script.turn_on
      data:
        entity_id: script.timed_lights_5min_off
    # Set new timer 
    - service: homeassistant.turn_on
      entity_id:
       - light.Lys_TV
       - light.Lys_stue
      data:
        brightness: 101

- alias: "lys bokhylle og bilder"
  initial_state: False
  trigger:
    - platform: state
      entity_id: binary_sensor.stue_lux
      to: 'off'
      for:
        hours: 2
    - platform: state
      entity_id: group.tracker
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: binary_sensor.stue_lux
      state: 'off'
      for:
        hours: 2
    - condition: state
      entity_id: group.tracker
      state: 'home'
    - condition: time
      after: '14:00:00'
      before: '23:00:00'
  action:
      service: homeassistant.turn_on
      entity_id: 
      - light.lys_bokhylle
      - light.lys_bilder
      - light.vindu

- alias: "lys bokhylle og bilder av"
  trigger:
    platform: time
    after: '23:30:00'
  action:
      service: homeassistant.turn_off
      entity_id: 
      - light.lys_bokhylle
      - light.lys_bilder
      - light.vindu

- alias: "Turn off light"
  trigger:
    - platform: state
      entity_id: group.tracker
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: binary_sensor.stue_lux
      to: 'on'
      for:
        minutes: 15
    - platform: state
      entity_id: script.timed_movement
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: group.tracker
      state: 'not_home'
    - condition: state
      entity_id: binary_sensor.stue_lux
      state: 'on'
    - condition: state
      entity_id: script.timed_movement
      state: 'off'
  action:
    - service: script.turn_off
      data: 
         entity_id: script.vekke_lys
    - service: homeassistant.turn_on
      entity_id: script.all_devices_off

- alias: "Turn off light night"
  trigger:
    - platform: time
      after: '01:00:00'
    - platform: state
      entity_id: script.timed_movement
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: script.timed_movement
      state: 'off'
    - condition: time
      after: '00:00:00'
      before: '07:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: script.all_devices_off

- alias: "Away lights"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -1
  condition:
    - condition: state
      entity_id: script.away_48
      state: 'off'
      for:
        minutes: 1
  action:
    - delay: '0{{ range(0,1) | random | int }}:{{ range(20,59) | random | int }}:00'
    - service: scene.turn_on
      data:
        entity_id: scene.Normal_lys   
    - delay: '0{{ range(0,3) | random | int }}:{{ range(20,59) | random | int }}:00'
    - service: homeassistant.turn_on
      entity_id: 
      - light.lys_bokhylle
      - light.lys_bilder
    - delay: '00:0{{ range(4,10) | random | int }}:00'
    - service: homeassistant.turn_on
      entity_id: script.all_devices_off
 
- alias: "Away lights veranda"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -4
  condition:
    - condition: state
      entity_id: script.away_48
      state: 'off'
      for:
        minutes: 1
  action:
    - delay: '00:{{ range(10,59) | random | int }}:{{ range(20,59) | random | int }}'
    - service: homeassistant.turn_on
      data:
        entity_id: light.veranda
        transition: 10
        brightness: 150
    - delay: '0{{ range(0,3) | random | int }}:{{ range(20,59) | random | int }}:00'
    - service: homeassistant.turn_off
      entity_id:
       - light.veranda

- alias: "Lys yttergang timer"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.movement1'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door'}
  condition:
   - condition: state
     entity_id: script.stovsuger_running
     state: 'off'
     for:
       minutes: 1
  action:
    - service: script.turn_off
      data: 
        entity_id: script.timed_lys_yttergang
    - service: script.turn_on
      data:
        entity_id: script.timed_lys_yttergang

- alias: "Lys yttergang"
  trigger:
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.movement1'}
   - platform: event
     event_type: button_pressed
     event_data: {'state': 'on', 'entity_id': 'switch.door'}
  condition:
   - condition: template
     value_template: '{% if states.automation.lys_yttergang.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.lys_yttergang.attributes.last_triggered)) > 2 }}  {% else %}  true {% endif %}'
   - condition: state
     entity_id: script.stovsuger_running
     state: 'off'
     for:
       minutes: 1
   - condition: state
     entity_id: light.yttergang
     state: 'off'
  action:
   - service: homeassistant.turn_on
     data:
       entity_id: light.yttergang
       transition: 0
       brightness: 90

- alias: 'Wake Me Up, lys stue'
  trigger:
   - platform: numeric_state
     entity_id: sensor.relative_alarm_time
     above: 0
  condition:
   - condition: state
     entity_id: automation.wake_me_up
     state: 'on'
   - condition: numeric_state
     entity_id: sun.sun
     value_template: '{{ state.attributes.elevation }}'
     below: 8
  action:
     service: scene.turn_on
     entity_id: scene.Normal_lys

- alias: "light"
  trigger:
    - platform: state
      entity_id: light.Lys_stue
      state: 'off'
    - platform: state
      entity_id: light.Lys_TV
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: script.light_turned_off_5min
    - delay: '00:00:01'
    - service: homeassistant.turn_on
      entity_id: script.light_turned_off_5min
