- alias: "Auto radio soverom"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.soverom
     state: 'idle'
     for:
       seconds: 1
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_soverom
    - service: input_select.select_option
      entity_id: input_select.radio_soverom
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_soverom

- alias: "Lys av pA soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'off', 'entity_id': 'switch.soverom_switch1'}
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
  condition:
    - condition: state
      entity_id: script.vekke_lys
      state: 'off'
    - condition: state
      entity_id: script.timed_lyd_soverom_5s
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.soverom1
        state: 'on'
      - condition: state
        entity_id: light.soverom2
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.sove_tid

- alias: "News pA soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
  condition:
    - condition: state
      entity_id: script.vekke_lys
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: script.vekke_lyd
    - service: homeassistant.turn_off
      entity_id: script.vekke_lys
    - service: homeassistant.turn_on
      entity_id: script.news_soverom

- alias: "Radio av soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
  condition:
    - condition: state
      entity_id: script.vekke_lys
      state: 'off'
    - condition: template
      value_template: '{{(as_timestamp(now())-as_timestamp(states.script.sove_lyd.last_triggered)) > 3600*1 }}'
  action:
   - service: media_player.turn_off
     entity_id: media_player.soverom    

- alias: "Lys soverom lyd 0"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
  condition:
    - condition: state
      entity_id: light.soverom1
      state: 'off'
    - condition: state
      entity_id: light.soverom2
      state: 'off'
  action:
    - service: script.turn_off
      data: 
         entity_id: script.timed_lyd_soverom_5s
    # Set new timer
    - service: script.turn_on
      data:
        entity_id: script.timed_lyd_soverom_5s

- alias: "Lys soverom lyd"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
  condition:
    - condition: state
      entity_id: script.timed_lyd_soverom_5s
      state: 'on'
  action:
  - service: script.turn_off
    data: 
       entity_id: script.sove_tid
  - service: homeassistant.turn_on
    entity_id:
      - light.soverom
    data:
      transition: 1
      brightness: 216
      xy_color: [0.5458, 0.4159]
  
- alias: "Lys soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.soverom_switch1'}
  action:
  - service: homeassistant.turn_on
    entity_id:
      - light.soverom
    data:
      transition: 0
      brightness: 1
      xy_color: [0.5458, 0.4159]
  - service: homeassistant.turn_on
    entity_id:
      - light.soverom
    data:
      transition: 15
      brightness: 216
      xy_color: [0.5458, 0.4159]
 
- alias: "Lys soverom door timer"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0x94597a)', 'entity_id': 'switch.movement_soverom_seng'}
  action:
    # Cancel ev. old timers 
    - service: script.turn_off
      data: 
        entity_id: script.timed_lys_soverom
    # Set new timer 
    - service: script.turn_on
      data:
        entity_id: script.timed_lys_soverom

- alias: "Lys soverom door trigger dag"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0x94597a)', 'entity_id': 'switch.movement_soverom_seng'}
  condition:
   - condition: template
     value_template: '{{(as_timestamp(now())-as_timestamp(states.script.leggetid_soverom.last_triggered)) > 3600*4 }}'
   - condition: or
     conditions:
     - condition: template
       value_template: '{{(as_timestamp(now())-as_timestamp(states.script.vekke_lys.last_triggered)) < 3600*4 }}'
     - condition: time
       after: '11:00:00'
       before: '23:00:00'
   - condition: state
     entity_id: light.soverom1
     state: 'off'
   - condition: state
     entity_id: light.soverom2
     state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.soverom
      data:
        brightness: 216
        xy_color: [0.5458, 0.4159]


- alias: "Nattlys"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0x94597a)', 'entity_id': 'switch.movement_soverom_seng'}
  condition:
   - condition: template
     value_template: '{{(as_timestamp(now())-as_timestamp(states.script.vekke_lys.last_triggered)) > 3600*4 }}'
   - condition: or
     conditions:
     - condition: template
       value_template: '{{(as_timestamp(now())-as_timestamp(states.script.leggetid_soverom.last_triggered)) < 3600*4 }}'
     - condition: time
       before: '11:00:00'
       after: '23:00:00'
   - condition: state
     entity_id: light.soverom1
     state: 'off'
   - condition: state
     entity_id: light.soverom2
     state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.soverom
      data:
        brightness: 10
        xy_color: [0.675,0.322]


- alias: "Lys soverom door trigger off"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_soverom
      state: 'off'
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'off', 'entity_id': 'switch.door_bedroom'}
  condition:
   - condition: state
     entity_id: light.soverom1
     state: 'on'
   - condition: state
     entity_id: light.soverom2
     state: 'on'
   - condition: state
     entity_id: script.leggetid_soverom
     state: 'off'
  action:
   - delay:
        seconds: 5
   # Cancel ev. old timers 
   - service: script.turn_off
     data: 
       entity_id: script.timed_lys_soverom
   - service: homeassistant.turn_off
     entity_id:
       - light.soverom
     data:
       transition: 10
