- alias: "Auto radio soverom"
  initial_state: False
  trigger:
   - platform: state
     entity_id: media_player.soverom
     to: 'idle'
     for:
       seconds: 1
  action:
    - service: homeassistant.turn_off
      entity_id: automation.auto_radio_soverom
    - service: media_player.volume_set
      data:
        entity_id: media_player.soverom
        volume_level: 0.4
    - service: input_select.select_option
      entity_id: input_select.radio_soverom
      data:
        option: "P3"
    - service: automation.trigger
      entity_id: automation.radio_soverom

- alias: "Sovetid pA soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.knapp_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
  condition:
    - condition: state
      entity_id: script.vekke_lys
      state: 'off'
    - condition: state
      entity_id: script.timed_lyd_soverom_5s
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.soverom1
        state: 'on'
      - condition: state
        entity_id: light.soverom2
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.sove_tid

- alias: "News pA soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.knapp_soverom'}
  condition:
    - condition: state
      entity_id: script.vekke_lys
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: script.vekke_lyd
    - service: homeassistant.turn_off
      entity_id: script.vekke_lys
    - service: homeassistant.turn_on
      entity_id: script.news_soverom

- alias: "Radio av soverom"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.knapp_soverom'}
  condition:
    - condition: state
      entity_id: script.vekke_lys
      state: 'off'
    - condition: template
      value_template: '{% if states.script.sove_lyd.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.script.sove_lyd.attributes.last_triggered)) > 3600 }}  {% else %}  true {% endif %}'
  action:
   - service: homeassistant.turn_off
     entity_id: automation.auto_radio_soverom
   - service: media_player.turn_off
     entity_id: media_player.soverom    

- alias: "Lys soverom lyd 0"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.knapp_soverom'}
  condition:
    - condition: state
      entity_id: light.soverom1
      state: 'off'
    - condition: state
      entity_id: light.soverom2
      state: 'off'
  action:
    - service: script.turn_off
      data: 
         entity_id: script.timed_lyd_soverom_5s
    # Set new timer
    - service: script.turn_on
      data:
        entity_id: script.timed_lyd_soverom_5s

- alias: "Lys soverom lyd"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'entity_id': 'switch.lyd_soverom', 'state': 'unknown command (0xd744fc)'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.knapp_soverom'}
  condition:
    - condition: state
      entity_id: script.timed_lyd_soverom_5s
      state: 'on'
  action:
  - service: script.turn_off
    data: 
       entity_id: script.sove_tid
  - service: homeassistant.turn_on
    entity_id:
      - light.soverom
    data:
      transition: 1
      brightness: 216
      xy_color: [0.5458, 0.4159]
  

- alias: "Lys soverom door timer"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0x94597a)', 'entity_id': 'switch.movement_soverom_seng'}
    - platform: state
      entity_id: binary_sensor.door_soverom
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00010aac89
      to: 'on'
  condition:
   - condition: state
     entity_id: script.leggetid_soverom
     state: 'off'
   - condition: state
     entity_id: script.vekke_lys
     state: 'off'
  action:
    # Cancel ev. old timers 
    - service: script.turn_off
      entity_id: script.timed_lys_soverom
    - service: script.turn_on
      entity_id: script.timed_lys_soverom

- alias: "Lys soverom door trigger dag"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0x94597a)', 'entity_id': 'switch.movement_soverom_seng'}
    - platform: state
      entity_id: binary_sensor.door_soverom
      to: 'on'
  condition:
   - condition: template
     value_template: '{% if states.script.leggetid_soverom.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.script.leggetid_soverom.attributes.last_triggered)) > 3600*4 }}  {% else %}  true {% endif %}'

   - condition: or
     conditions:
     - condition: template
       value_template: '{% if states.script.vekke_lys.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.script.vekke_lys.attributes.last_triggered)) < 3600*4 }}  {% else %}  false {% endif %}'
     - condition: time
       after: '11:00:00'
       before: '23:00:00'

   - condition: state
     entity_id: light.soverom1
     state: 'off'
   - condition: state
     entity_id: light.soverom2
     state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.lys_soverom_door_trigger_dag
    - service: homeassistant.turn_on
      entity_id:
        - light.soverom
      data:
        xy_color: [0.5458,0.4159]
        brightness: 255
    - delay: 00:00:30
    - service: homeassistant.turn_on
      entity_id: automation.lys_soverom_door_trigger_dag

- alias: "Nattlys"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'on', 'entity_id': 'switch.door_bedroom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0xdb153a)', 'entity_id': 'switch.movement_soverom'}
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'unknown command (0x94597a)', 'entity_id': 'switch.movement_soverom_seng'}
  condition:
   - condition: state
     entity_id: input_boolean.nattlys
     state: 'on'
  
   - condition: template
     value_template: '{% if states.script.vekke_lys.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.script.vekke_lys.attributes.last_triggered)) > 3600*4 }}  {% else %}  true {% endif %}'
   - condition: template
     value_template: '{% if states.script.leggetid_soverom.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.script.leggetid_soverom.attributes.last_triggered)) > 60*2}}  {% else %}  true {% endif %}'
   - condition: template
     value_template: '{% if states.automation.lys_soverom_door_timer.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.lys_soverom_door_timer.attributes.last_triggered)) > 20}}  {% else %}  true {% endif %}'

   - condition: or
     conditions:
     - condition: template
       value_template: '{% if states.script.leggetid_soverom.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.script.leggetid_soverom.attributes.last_triggered)) < 3600*4 }}  {% else %}  false {% endif %}'
     - condition: time
       before: '11:00:00'
       after: '23:00:00'

   - condition: state
     entity_id: light.soverom1
     state: 'off'
   - condition: state
     entity_id: light.soverom2
     state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.nattlys
    - service: homeassistant.turn_on
      entity_id:
        - light.soverom
      data:
        brightness: 10
        xy_color: [0.675,0.322]
    - delay: 00:00:30
    - service: homeassistant.turn_on
      entity_id: automation.nattlys


- alias: "Lys soverom door trigger off"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'off', 'entity_id': 'switch.door_bedroom'}
    - platform: state
      entity_id: binary_sensor.door_soverom
      to: 'off'
  condition:
   - condition: state
     entity_id: light.soverom1
     state: 'on'
   - condition: state
     entity_id: light.soverom2
     state: 'on'
   - condition: state
     entity_id: script.leggetid_soverom
     state: 'off'
   - condition: state
     entity_id: script.vekke_lys
     state: 'off'
  action:
   - delay:
        seconds: 1
   - service: script.turn_off
     entity_id: script.timed_lys_soverom
   - service: homeassistant.turn_off
     entity_id: light.soverom
     data:
       transition: 10

- alias: "Temporarly disable night light"
  trigger:
   - platform: state
     entity_id: light.soverom1
     to: 'off'
   - platform: state
     entity_id: light.soverom2
     to: 'off'
  condition:
   - condition: state
     entity_id: automation.nattlys
     state: 'on'
  action:
   - service: homeassistant.turn_off
     entity_id: automation.nattlys
   - delay: 00:01:00
   - service: homeassistant.turn_on
     entity_id: automation.nattlys


- alias: "Lysstyrke soverom, knapp"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: long_click_press
  condition:
   - condition: state
     entity_id: light.soverom1
     state: 'off'
   - condition: state
     entity_id: light.soverom2
     state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: script.brightness_soverom

- alias: "Lysstyrke soverom stopp, knapp"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: hold
  condition:
  action:
  - service: homeassistant.turn_off
    entity_id: script.brightness_soverom
  - service: homeassistant.turn_off
    entity_id: script.brightness_soverom_temp

- alias: "Lys av pA soverom, knapp"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: long_click_press
  condition:
   - condition: or
     conditions:
     - condition: state
       entity_id: light.soverom1
       state: 'on'
     - condition: state
       entity_id: light.soverom2
       state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id:
      - light.soverom
      - script.vekke_lys
      - script.leggetid_soverom
      - script.leggetid_soverom_temp
  - service: homeassistant.turn_off
    entity_id:
      - light.soverom

- alias: "Klokke soverom"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: single
  action:
    - service: media_player.turn_on
      entity_id: media_player.soverom
    - service: media_player.volume_set
      data:
        entity_id: media_player.soverom
        volume_level: 0.55
    - service: tts.google_say
      entity_id: media_player.soverom
      data_template:
        message: 'Klokken er {{ now().hour}}  {{ "%0.02d" | format(now().strftime("%-M") | int) }}'
        cache: false

