
- alias: "Lysstyrke soverom, knapp"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: long_click_press
  condition:
   - condition: state
     entity_id: light.soverom1
     state: 'off'
   - condition: state
     entity_id: light.soverom2
     state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: script.brightness_soverom

- alias: "Lys av pA soverom, knapp"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: long_click_press
  condition:
   - condition: or
     conditions:
     - condition: state
       entity_id: light.soverom1
       state: 'on'
     - condition: state
       entity_id: light.soverom2
       state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id:
      - light.soverom
      - script.vekke_lys
  - service: homeassistant.turn_off
    entity_id:
      - light.soverom


- alias: "Lysstyrke soverom stopp, knapp"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: hold
  condition:
  action:
  - service: homeassistant.turn_off
    entity_id: script.brightness_soverom, script.brightness_soverom_temp


- alias: "Klokke soverom"
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001165868
        click_type: single
  action:
    - service: media_player.turn_on
      entity_id: media_player.soverom
    - service: media_player.volume_set
      data:
        entity_id: media_player.soverom
        volume_level: 0.55
    - service: tts.google_say
      entity_id: media_player.soverom
      data_template:
        message: 'Klokken er {{ now().hour}}  {{ "%0.02d" | format(now().strftime("%-M") | int) }}'
        cache: false
