- alias: "steketermometer fisk"
  trigger:
   - platform: state
     entity_id: input_select.steketermometer
     to: 'Fisk (50*)'
  action:
  - service: input_number.set_value
    data:
      entity_id: "input_number.temp_steketermometer"
      value: "50"
        
- alias: "steketermometer kylling"
  trigger:
   - platform: state
     entity_id: input_select.steketermometer
     to: 'Kylling (70*)'
  action:
  - service: input_number.set_value
    data:
      entity_id: "input_number.temp_steketermometer"
      value: "70"
