sensor:
  - platform: template
    sensors:
      timer_minutes:
        friendly_name: 'Timer minutes'
        value_template: '{{states.input_slider.timer_minutes.state|round(2)}}'
        entity_id: 
         - input_slider.timer_minutes

script:
  timer:
    sequence:
    - delay: '00:00:15'
    - service: input_slider.select_value
      data_template:
        value: '{{ states.input_slider.timer_minutes.state|float - 0.25 }}'
        entity_id: input_slider.timer_minutes

automation:
  - alias: "timer"
    trigger:
      platform: state
      entity_id: input_slider.timer_minutes
    condition:
     - condition: template
       value_template: '{{ states.input_slider.timer_minutes.state|float > 0}}'
    action:
    - service: script.turn_off
      entity_id: script.timer
    - service: script.turn_on
      entity_id: script.timer

  - alias: "timer execute"
    trigger:
      platform: state
      entity_id: input_slider.timer_minutes
    condition:
     - condition: template
       value_template: '{{ states.input_slider.timer_minutes.state|float == 0.25}}'
    action:
    - service: media_player.turn_on
      entity_id: media_player.stue
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue
        volume_level: 0.9
    - delay: '00:00:15'
    - service: tts.google_say
      entity_id: media_player.stue
      data_template:
        message: 'Nedtelt tid har n책 g책tt'
        cache: true
    - service: media_player.turn_on
      entity_id: script.light_notify
    - delay: '00:00:01'
    - service: media_player.turn_on
      entity_id: script.light_notify
    - delay: '00:00:01'
    - service: media_player.turn_on
      entity_id: script.light_notify
    - service: tts.google_say
      entity_id: media_player.stue
      data_template:
        message: 'Nedtelt tid har n책 g책tt'
        cache: true



input_slider:
  timer_minutes:
    name: Minutes
    icon: mdi:timer
    initial: 0
    min: 0
    max: 30
    step: 1
